### PR TITLE
Remove batch file and generate graphs through maven

### PR DESCRIPTION
**Pull request by michael-simons**
Run with `mvn clean package` to get desired graphs.

Hi @schauder would you mind putting 0.1.4 on central? There's no need for a plugin to create the graphs through a simple maven config.

### CODE REVIEW

**Comment by FrVaBe** [comment]
Thanks for contribution. Merged your changes to a 'run-via-maven' branch instead of master (hope I did it right). Will try to also keep the batch file and have to adjust documentation before merging to master.
Hope to see you soon. All the best. Franz

**Comment by michael-simons** [comment]
Everything's fine :) It was an unasked contribution anyway. 
I'm looking around for something that can create images from GraphML using an automated process.

**Comment by FrVaBe** [comment]
Note: The degraph application is not meant to be avaiblabe via Maven central (see [here](https://twitter.com/jensschauder/status/835966165042270208)). The application binaries are hosted on [Bintray](https://bintray.com/schauder/schauderhaft-de/Degraph). Maybe graphml file can also be generated with degraph-check. More investigation needed.

**Comment by schauder** [comment]
check does create graphml on failure. The feature for graphml creation independent of outcome is unfortunately broken,

**Pull request closed without merging**
